# Generated by Django 5.2 on 2025-09-24 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0003_alter_houseuser_type_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nombre del método de pago (ej: Efectivo, Transferencia, Tarjeta)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del método de pago')),
                ('is_active', models.BooleanField(default=True, help_text='Si el método de pago está disponible para usar')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(help_text='Número secuencial de la cuota')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto a pagar', max_digits=12)),
                ('due_date', models.DateField(help_text='Fecha límite de pago')),
                ('paid_date', models.DateTimeField(blank=True, help_text='Fecha y hora de pago (null si no pagada)', null=True)),
                ('reference', models.CharField(blank=True, help_text='Referencia o comprobante de pago', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagada'), ('OVERDUE', 'Vencida'), ('CANCELLED', 'Cancelada')], default='PENDING', help_text='Estado actual de la cuota', max_length=20)),
                ('period_month', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Mes del período (1-12)')),
                ('period_year', models.PositiveIntegerField(help_text='Año del período')),
                ('is_automatic', models.BooleanField(default=True, help_text='Si fue generada automáticamente por el sistema')),
                ('house_user', models.ForeignKey(help_text='Relación usuario-vivienda responsable del pago', on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='house.houseuser')),
                ('payment_method', models.ForeignKey(blank=True, help_text='Método de pago utilizado (requerido cuando status=PAID)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='quote.paymentmethod')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['-period_year', '-period_month', 'number'],
                'indexes': [models.Index(fields=['house_user', 'status'], name='quote_quote_house_u_445ec7_idx'), models.Index(fields=['due_date', 'status'], name='quote_quote_due_dat_d817d2_idx'), models.Index(fields=['period_year', 'period_month'], name='quote_quote_period__2c44d6_idx')],
                'unique_together': {('house_user', 'period_month', 'period_year', 'number')},
            },
        ),
    ]
