# Generated by Django 5.2 on 2025-09-24 16:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_alter_houseuser_type_house'),
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('gateway_type', models.CharField(choices=[('mercadopago', 'MercadoPago'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank_transfer', 'Transferencia Bancaria')], max_length=50)),
                ('config_data', models.JSONField(default=dict, help_text='Configuración de la pasarela (API keys, webhooks, etc.)')),
                ('bank_info', models.JSONField(blank=True, default=dict, help_text='Información bancaria para transferencias manuales')),
                ('is_active', models.BooleanField(default=True)),
                ('is_test_mode', models.BooleanField(default=True, help_text='Si está en modo de prueba o producción')),
            ],
            options={
                'verbose_name': 'Pasarela de Pago',
                'verbose_name_plural': 'Pasarelas de Pago',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-period_year', '-period_month', 'due_date'], 'verbose_name': 'Cuota', 'verbose_name_plural': 'Cuotas'},
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('house_user', 'period_month', 'period_year')},
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='requires_gateway',
            field=models.BooleanField(default=False, help_text='Si requiere pasarela de pago externa (MercadoPago, Stripe, etc.)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_data',
            field=models.JSONField(blank=True, default=dict, help_text='Datos adicionales del pago (respuesta de pasarela, etc.)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Referencia, comprobante o ID de transacción', max_length=200),
        ),
        migrations.AlterField(
            model_name='quote',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Método de pago utilizado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='quote.paymentmethod'),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_gateway',
            field=models.ForeignKey(blank=True, help_text='Pasarela de pago utilizada (si aplica)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='quote.paymentgateway'),
        ),
        migrations.RemoveField(
            model_name='quote',
            name='number',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='reference',
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(help_text='ID único de la transacción (generado por nosotros o por la pasarela)', max_length=200, unique=True)),
                ('external_id', models.CharField(blank=True, help_text='ID de la transacción en la pasarela externa', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto de la transacción', max_digits=12)),
                ('currency', models.CharField(default='USD', help_text='Moneda de la transacción', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', help_text='Estado de la transacción', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Respuesta completa de la pasarela de pago')),
                ('payment_details', models.JSONField(blank=True, default=dict, help_text='Detalles adicionales del pago (método, últimos 4 dígitos, etc.)')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Fecha de procesamiento de la transacción', null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Fecha de confirmación del pago', null=True)),
                ('payment_gateway', models.ForeignKey(blank=True, help_text='Pasarela utilizada para el pago', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='quote.paymentgateway')),
                ('quote', models.ForeignKey(help_text='Cuota relacionada con esta transacción', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='quote.quote')),
            ],
            options={
                'verbose_name': 'Transacción de Pago',
                'verbose_name_plural': 'Transacciones de Pago',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='quote_payme_transac_f8cc2e_idx'), models.Index(fields=['external_id'], name='quote_payme_externa_35c842_idx'), models.Index(fields=['status', 'created_at'], name='quote_payme_status_6219fc_idx')],
            },
        ),
    ]
