# Generated by Django 5.2 on 2025-09-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_paymentgateway_alter_quote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='manual_verification',
            field=models.BooleanField(default=False, help_text='Si requiere verificación manual del administrador'),
        ),
    ]
