# Generated by Django 5.2 on 2025-09-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_paymentmethod_manual_verification'),
    ]

    operations = [
    ]
