# Generated by Django 5.2 on 2025-09-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_auto_20250924_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción o concepto de la cuota (ej: Cuota mensual enero 2024)'),
        ),
    ]
