# Generated by Django 5.2 on 2025-09-26 15:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nombre del tipo de servicio', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción del tipo de servicio')),
                ('is_active', models.BooleanField(default=True, help_text='Si el tipo de servicio está disponible')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto a pagar', max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('CLP', 'Peso Chileno'), ('EUR', 'Euro')], default='USD', help_text='Moneda del pago', max_length=3)),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', help_text='Estado actual del pago', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='Fecha límite de pago (opcional)', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Fecha de pago exitoso', null=True)),
                ('payment_id', models.CharField(help_text='ID único interno del pago', max_length=100, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='ID del PaymentIntent de Stripe', max_length=200, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del pago (referencia externa, etc.)')),
                ('user', models.ForeignKey(help_text='Usuario que realiza el pago', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(help_text='Tipo de servicio a pagar', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='service.servicetype')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(help_text='Tipo de evento (created, processing, completed, failed, etc.)', max_length=50)),
                ('message', models.TextField(help_text='Descripción del evento')),
                ('stripe_event_id', models.CharField(blank=True, help_text='ID del evento de Stripe (si aplica)', max_length=200, null=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del evento')),
                ('payment', models.ForeignKey(help_text='Pago relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='service.payment')),
            ],
            options={
                'verbose_name': 'Log de Pago',
                'verbose_name_plural': 'Logs de Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='service_pay_user_id_4ed790_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_id'], name='service_pay_payment_cd2024_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='service_pay_stripe__58c72d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='service_pay_status_8fe36a_idx'),
        ),
    ]
