# Generated by Django 5.2 on 2025-09-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoai',
            name='acceso',
        ),
        migrations.DeleteModel(
            name='Acceso',
        ),
    ]
