# Generated by Django 5.2 on 2025-09-30 21:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_system', '0002_remove_acceso_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=20, verbose_name='Tipo de Acceso')),
                ('descripcion', models.TextField(verbose_name='Descripción del Acceso')),
                ('imagen_s3_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen en S3')),
                ('confianza', models.FloatField(help_text='Porcentaje de confianza de la detección AI', verbose_name='Confianza (%)')),
                ('fuente_deteccion', models.CharField(default='frontend', help_text='frontend, camara, upload, etc.', max_length=50, verbose_name='Fuente')),
                ('datos_adicionales', models.JSONField(blank=True, default=dict, help_text='Información específica del acceso', verbose_name='Datos Adicionales')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Acceso AI',
                'verbose_name_plural': 'Accesos AI',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='ai_system_a_created_24dc2a_idx'), models.Index(fields=['tipo'], name='ai_system_a_tipo_bc3804_idx'), models.Index(fields=['usuario'], name='ai_system_a_usuario_eca0ff_idx')],
            },
        ),
    ]
