# Generated by Django 5.2 on 2025-09-26 04:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('cost_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_reservable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('available_from', models.TimeField(default='06:00')),
                ('available_to', models.TimeField(default='22:00')),
                ('available_monday', models.BooleanField(default=True)),
                ('available_tuesday', models.BooleanField(default=True)),
                ('available_wednesday', models.BooleanField(default=True)),
                ('available_thursday', models.BooleanField(default=True)),
                ('available_friday', models.BooleanField(default=True)),
                ('available_saturday', models.BooleanField(default=True)),
                ('available_sunday', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Área Común',
                'verbose_name_plural': 'Áreas Comunes',
            },
        ),
        migrations.CreateModel(
            name='CommonAreaRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('common_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='condominium.commonarea')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'administrator'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regla de Área Común',
                'verbose_name_plural': 'Reglas de Áreas Comunes',
            },
        ),
        migrations.CreateModel(
            name='GeneralRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'administrator'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regla General',
                'verbose_name_plural': 'Reglas Generales',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('purpose', models.TextField(blank=True, null=True)),
                ('estimated_attendees', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada'), ('completed', 'Completada')], default='pending', max_length=20)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['administrator', 'guard']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reservations', to=settings.AUTH_USER_MODEL)),
                ('common_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='condominium.commonarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'unique_together': {('common_area', 'reservation_date', 'start_time')},
            },
        ),
    ]
