# Generated by Django 5.2 on 2025-09-30 16:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('purpose', models.TextField(blank=True, null=True)),
                ('estimated_attendees', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pendiente'),
                        ('approved', 'Aprobada'),
                        ('rejected', 'Rechazada'),
                        ('cancelled', 'Cancelada'),
                        ('completed', 'Completada')
                    ],
                    default='pending',
                    max_length=20
                )),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(
                    blank=True,
                    limit_choices_to={'role__in': ['administrator', 'guard']},
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='approved_reservations',
                    to=settings.AUTH_USER_MODEL
                )),
                ('common_area', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reservations',
                    to='condominium.commonarea'
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reservations',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'unique_together': {('common_area', 'reservation_date', 'start_time')},
            },
        ),
    ]
