# Generated by Django 5.2 on 2025-09-26 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0002_remove_parkingspace_assigned_user_and_more'),
    ]

    operations = [
        # Eliminar modelo ParkingReservation primero (tiene FK a ParkingSpace)
        migrations.DeleteModel(
            name='ParkingReservation',
        ),
        # Eliminar modelo ParkingSpace
        migrations.DeleteModel(
            name='ParkingSpace',
        ),
    ]
