# Generated by Django 5.2 on 2025-09-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_enabled',
            field=models.BooleanField(default=False, help_text='¿Está habilitado para usar la aplicación móvil?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrador'), ('owner', 'Propietario'), ('resident', 'Viviente'), ('guard', 'Guardia'), ('visitor', 'Visitante')], max_length=20),
        ),
    ]
