# Generated by Django 5.2 on 2025-09-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrador'), ('owner', 'Propietario'), ('resident', 'Inquilino'), ('guard', 'Guardia'), ('visitor', 'Visitante')], max_length=20),
        ),
    ]
