# Generated by Django 5.2 on 2025-09-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_role'),
        ('user', '0002_user_app_enabled_alter_user_role'),
    ]

    operations = [
    ]
