# Generated by Django 5.2 on 2025-09-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_merge_20250930_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='s3_face_folder_url',
            field=models.CharField(blank=True, help_text='URL/carpeta S3 donde están almacenadas las imágenes faciales del usuario', max_length=300, null=True, verbose_name='Carpeta S3 de rostros'),
        ),
    ]
