# Generated by Django 5.2 on 2025-09-24 12:38

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Vivienda', 'verbose_name_plural': 'Viviendas'},
        ),
        migrations.AlterModelOptions(
            name='houseuser',
            options={'verbose_name': 'Usuario de Vivienda', 'verbose_name_plural': 'Usuarios de Vivienda'},
        ),
        migrations.AlterUniqueTogether(
            name='houseuser',
            unique_together={('house', 'user')},
        ),
        migrations.AddField(
            model_name='house',
            name='foto_url',
            field=models.URLField(blank=True, help_text='URL de la foto principal', null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='price_base',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio base para publicaciones', max_digits=12),
        ),
        migrations.AddField(
            model_name='houseuser',
            name='end_date',
            field=models.DateField(blank=True, help_text='Fecha de fin de la relación (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='houseuser',
            name='inicial_date',
            field=models.DateField(default=datetime.date.today, help_text='Fecha de inicio de la relación con la vivienda'),
        ),
        migrations.AddField(
            model_name='houseuser',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='Usuario responsable del pago de cuotas'),
        ),
        migrations.AddField(
            model_name='houseuser',
            name='price_responsibility',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio que debe pagar este usuario (puede diferir del precio base)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='code',
            field=models.CharField(default='SIN-CODIGO', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='nro_bathrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='house',
            name='nro_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='houseuser',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_users', to='house.house'),
        ),
        migrations.AlterField(
            model_name='houseuser',
            name='type_house',
            field=models.CharField(choices=[('OWNER', 'Propietario'), ('TENANT', 'Inquilino')], default='OWNER', max_length=20),
        ),
        migrations.AlterField(
            model_name='houseuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_houses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Sin nombre', max_length=100)),
                ('species', models.CharField(default='Desconocido', help_text='Ej: Perro, Gato, Ave, etc.', max_length=50)),
                ('breed', models.CharField(blank=True, help_text='Raza específica (opcional)', max_length=100)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='house.house')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate', models.CharField(default='SIN-PLACA', help_text='Placa única del vehículo', max_length=20, unique=True)),
                ('brand', models.CharField(default='Desconocida', help_text='Marca del vehículo', max_length=50)),
                ('model', models.CharField(default='Desconocido', help_text='Modelo del vehículo', max_length=50)),
                ('color', models.CharField(default='Sin color', max_length=30)),
                ('type_vehicle', models.CharField(choices=[('SEDAN', 'Sedán'), ('SUV', 'SUV'), ('HATCHBACK', 'Hatchback'), ('PICKUP', 'Camioneta'), ('MOTORCYCLE', 'Motocicleta'), ('TRUCK', 'Camión'), ('VAN', 'Van')], default='SEDAN', max_length=30)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='house.house')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.RemoveField(
            model_name='houseuser',
            name='assignment_date',
        ),
        migrations.RemoveField(
            model_name='houseuser',
            name='price',
        ),
        migrations.RemoveField(
            model_name='houseuser',
            name='principal',
        ),
    ]
