# Generated by Django 5.2 on 2025-09-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_house_options_alter_houseuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseuser',
            name='type_house',
            field=models.CharField(choices=[('OWNER', 'Propietario'), ('RESIDENT', 'Inquilino')], default='RESIDENT', max_length=20),
        ),
    ]
