# Generated by Django 5.2 on 2025-09-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_alter_houseuser_type_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseuser',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='houseuser',
            name='is_principal',
            field=models.BooleanField(default=False, help_text='Usuario principal responsable del pago de cuotas'),
        ),
        migrations.AlterField(
            model_name='houseuser',
            name='price_responsibility',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio que debe pagar este usuario principal (puede diferir del precio base)', max_digits=12, null=True),
        ),
    ]
