# Generated by Django 5.2 on 2025-09-25 21:12

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('owners', models.ManyToManyField(blank=True, limit_choices_to={'role': 'owner'}, related_name='owned_properties', to=settings.AUTH_USER_MODEL)),
                ('residents', models.ManyToManyField(blank=True, limit_choices_to={'role': 'resident'}, related_name='resident_properties', to=settings.AUTH_USER_MODEL)),
                ('visitors', models.ManyToManyField(blank=True, limit_choices_to={'role': 'visitor'}, related_name='visited_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
