# Generated by Django 5.2 on 2025-09-29 19:06

import django.db.models.deletion
import property.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Sin nombre', max_length=100)),
                ('species', models.CharField(default='Desconocido', help_text='Ej: Perro, Gato, Ave, etc.', max_length=50)),
                ('breed', models.CharField(blank=True, help_text='Raza específica (opcional)', max_length=100)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
        migrations.CreateModel(
            name='PropertyQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto a pagar', max_digits=12)),
                ('description', models.TextField(blank=True, help_text='Descripción o concepto de la cuota')),
                ('due_date', models.DateField(help_text='Fecha límite de pago')),
                ('paid_date', models.DateTimeField(blank=True, help_text='Fecha y hora de pago (null si no pagada)', null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Referencia, comprobante o ID de transacción', max_length=200)),
                ('payment_data', models.JSONField(blank=True, default=property.models.default_payment_data, help_text='Datos adicionales del pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('overdue', 'Vencido'), ('cancelled', 'Cancelado'), ('partial', 'Pago Parcial')], default='pending', help_text='Estado actual de la cuota', max_length=20)),
                ('period_month', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Mes del período (1-12)')),
                ('period_year', models.PositiveIntegerField(help_text='Año del período')),
                ('is_automatic', models.BooleanField(default=True, help_text='Si fue generada automáticamente por el sistema')),
            ],
            options={
                'verbose_name': 'Cuota de Propiedad',
                'verbose_name_plural': 'Cuotas de Propiedades',
                'ordering': ['-period_year', '-period_month', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate', models.CharField(default='SIN-PLACA', help_text='Placa única del vehículo', max_length=20, unique=True)),
                ('brand', models.CharField(default='Desconocida', help_text='Marca del vehículo', max_length=50)),
                ('model', models.CharField(default='Desconocido', help_text='Modelo del vehículo', max_length=50)),
                ('color', models.CharField(default='Sin color', max_length=30)),
                ('type_vehicle', models.CharField(choices=[('sedan', 'Sedán'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('pickup', 'Pickup'), ('motorcycle', 'Motocicleta'), ('bicycle', 'Bicicleta'), ('van', 'Furgoneta'), ('truck', 'Camión'), ('other', 'Otro')], default='sedan', max_length=30)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Propiedad', 'verbose_name_plural': 'Propiedades'},
        ),
        migrations.AddField(
            model_name='property',
            name='is_payment_enabled',
            field=models.BooleanField(default=False, help_text='Si está habilitado el cobro automático de cuotas'),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto mensual a cobrar (cuota de mantenimiento, alquiler, etc.)', max_digits=12),
        ),
        migrations.AddField(
            model_name='property',
            name='payment_due_day',
            field=models.PositiveIntegerField(default=1, help_text='Día del mes/período en que vence el pago (1-31)'),
        ),
        migrations.AddField(
            model_name='property',
            name='payment_frequency',
            field=models.CharField(choices=[('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], default='monthly', help_text='Frecuencia de pago de las cuotas', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('for_sale', 'En Venta'), ('sold', 'Vendida'), ('for_rent', 'En Alquiler'), ('rented', 'Alquilada'), ('owned_and_rented', 'Propietario que Alquila'), ('under_construction', 'En Construcción'), ('available', 'Disponible')], default='available', help_text='Estado actual de la propiedad', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='owners',
            field=models.ManyToManyField(blank=True, help_text='Propietarios de la propiedad (si está vendida o en proceso de pago)', limit_choices_to={'role': 'owner'}, related_name='owned_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='residents',
            field=models.ManyToManyField(blank=True, help_text='Residentes/inquilinos de la propiedad', limit_choices_to={'role': 'resident'}, related_name='resident_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='visitors',
            field=models.ManyToManyField(blank=True, help_text='Visitantes autorizados', limit_choices_to={'role': 'visitor'}, related_name='visited_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='property_pr_status_b98bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_payment_enabled', 'status'], name='property_pr_is_paym_a6ffa5_idx'),
        ),
        migrations.AddField(
            model_name='pet',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='property.property'),
        ),
        migrations.AddField(
            model_name='propertyquote',
            name='related_property',
            field=models.ForeignKey(help_text='Propiedad asociada a la cuota', on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='property.property'),
        ),
        migrations.AddField(
            model_name='propertyquote',
            name='responsible_user',
            field=models.ForeignKey(help_text='Usuario responsable del pago', on_delete=django.db.models.deletion.PROTECT, related_name='property_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='property.property'),
        ),
        migrations.AddIndex(
            model_name='propertyquote',
            index=models.Index(fields=['related_property', 'status'], name='property_pr_related_2e1a89_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyquote',
            index=models.Index(fields=['responsible_user', 'status'], name='property_pr_respons_d2ad86_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyquote',
            index=models.Index(fields=['due_date', 'status'], name='property_pr_due_dat_5bf9c9_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyquote',
            index=models.Index(fields=['period_year', 'period_month'], name='property_pr_period__76832d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyquote',
            unique_together={('related_property', 'responsible_user', 'period_month', 'period_year')},
        ),
    ]
