# Generated by Django 5.2 on 2025-09-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_pet_propertyquote_vehicle_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(default=0, help_text='Número de baños'),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(default=0, help_text='Número de dormitorios'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.PositiveIntegerField(blank=True, help_text='Número de piso (para apartamentos)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='furnished',
            field=models.BooleanField(default=False, help_text='¿Está amueblada?'),
        ),
        migrations.AddField(
            model_name='property',
            name='garage_spaces',
            field=models.PositiveIntegerField(default=0, help_text='Número de espacios de estacionamiento'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_balcony',
            field=models.BooleanField(default=False, help_text='¿Tiene balcón?'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_elevator',
            field=models.BooleanField(default=False, help_text='¿Tiene acceso a ascensor?'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_garage',
            field=models.BooleanField(default=False, help_text='¿Tiene garage?'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_terrace',
            field=models.BooleanField(default=False, help_text='¿Tiene terraza?'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_yard',
            field=models.BooleanField(default=False, help_text='¿Tiene patio/jardín?'),
        ),
        migrations.AddField(
            model_name='property',
            name='pets_allowed',
            field=models.BooleanField(default=True, help_text='¿Se permiten mascotas?'),
        ),
        migrations.AddField(
            model_name='property',
            name='square_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Metros cuadrados de la propiedad', max_digits=8, null=True),
        ),
    ]
