# Generated by Django 5.2 on 2025-09-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_bathrooms_property_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='building_or_block',
            field=models.CharField(blank=True, help_text='Número de edificio, torre, manzana o bloque', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_number',
            field=models.CharField(default='S/N', help_text='Número específico de la propiedad (apartamento, casa, local, etc.)', max_length=20),
        ),
    ]
