# Generated by Django 5.2 on 2025-10-01 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_building_or_block_property_property_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='propertyquote',
            name='property_pr_respons_d2ad86_idx',
        ),
        migrations.AlterUniqueTogether(
            name='propertyquote',
            unique_together={('related_property', 'period_month', 'period_year')},
        ),
        migrations.AddField(
            model_name='propertyquote',
            name='paid_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó el pago (debe ser uno de los responsables)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_property_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyquote',
            name='responsible_users',
            field=models.ManyToManyField(help_text='Usuarios responsables del pago (cualquiera puede pagar por todos)', related_name='property_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='propertyquote',
            name='responsible_user',
        ),
    ]
