# Generated by Django 5.2 on 2025-10-01 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0001_initial'),
        ('property', '0005_remove_propertyquote_property_pr_respons_d2ad86_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyquote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cuota de Pago', 'verbose_name_plural': 'Cuotas de Pago'},
        ),
        migrations.AlterUniqueTogether(
            name='propertyquote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='propertyquote',
            name='payment_type',
            field=models.CharField(choices=[('property', 'Cuota de Propiedad'), ('reservation', 'Pago de Reserva')], default='property', help_text='Tipo de pago', max_length=20),
        ),
        migrations.AddField(
            model_name='propertyquote',
            name='related_reservation',
            field=models.ForeignKey(blank=True, help_text='Reserva asociada al pago (solo para pagos de reservas)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_quotes', to='condominium.reservation'),
        ),
        migrations.AlterField(
            model_name='propertyquote',
            name='period_month',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Mes del período (1-12) - Solo para pagos de propiedades', null=True),
        ),
        migrations.AlterField(
            model_name='propertyquote',
            name='period_year',
            field=models.PositiveIntegerField(blank=True, help_text='Año del período - Solo para pagos de propiedades', null=True),
        ),
        migrations.AlterField(
            model_name='propertyquote',
            name='related_property',
            field=models.ForeignKey(blank=True, help_text='Propiedad asociada a la cuota (solo para pagos de propiedades)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='property.property'),
        ),
        migrations.AddIndex(
            model_name='propertyquote',
            index=models.Index(fields=['related_reservation', 'status'], name='property_pr_related_fdd957_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyquote',
            index=models.Index(fields=['payment_type'], name='property_pr_payment_1af999_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyquote',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_type', 'property')), fields=('related_property', 'period_month', 'period_year'), name='unique_property_period'),
        ),
        migrations.AddConstraint(
            model_name='propertyquote',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_type', 'reservation')), fields=('related_reservation',), name='unique_reservation_payment'),
        ),
    ]
